### ISSUE TITLE
WebStor 1.0b.1.5 is availble

### ISSUE THREAD

**Issue by oblaksoft** [klokan/webstor#1]
The new version of WebStor that supports Google Cloud Storage (in addition to Amazon S3 and Eucalyptus Walrus) is available for free download at http://www.oblaksoft.com/downloads/.

**Comment by klokan** [comment]
Updated to 1.0b.1.5. Thanks for the report. BTW support for RackSpace Files would be great.

Don't you want to maintain an official GitHub repository for this code on http://www.github.com/oblaksoft/?
