### ISSUE TITLE
Upload to DropBox with REST API - with progressbar for a large file

### ISSUE THREAD

**Issue by klokan** [klokan/webstor#10]
We need to upload individual MBTiles file which can be pretty large into DropBox with their REST API.
Unfortunately they do not have an C/C++ API.
Either we link it against another language or we add implementation of DropBox API into webstore - at least for uploading large files with progress bar.

To be confirmed.

**Comment by xrosecky** [comment]
DropBox uses OAuth v1.0 for authentication, in C++ you can use this library (pure implementation with no external dependencies):

https://github.com/sirikata/liboauthcpp

**Comment by klokan** [comment]
This has been already implemented now:
https://github.com/binaryking/nub
