### ISSUE TITLE
Buckets and resources should be public

### ISSUE THREAD

**Issue by xrosecky** [klokan/webstor#11]
Buckets and resources should be public

**Comment by klokan** [comment]
I recommend setting the bucket permission to “full control by owner” only and setting the permissions of the files within the bucket to “full control by owner, read access for everyone”. This will prevent people from being able to browse/list the files in your bucket.

Example (made manually):
http://webstormanual.s3-website-us-east-1.amazonaws.com/
http://webstormanual.s3.amazonaws.com/
http://s3.amazonaws.com/webstormanual

**Comment by xrosecky** [comment]
Should be fixed in cf45dc1bf56aad9334e9914793e6c1eb7334943b.

http://webstortest3.s3.amazonaws.com/ - no directory listing
http://webstortest3.s3.amazonaws.com/grandcanyon/11/385/804.png - uploaded files can be downloaded by everyone
