### ISSUE TITLE
Create index.html and set it as indexfile

### ISSUE THREAD

**Issue by xrosecky** [klokan/webstor#12]
Create index.html (empty for now) and set it as indexfile using PUT Bucket website:

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTwebsite.html

**Comment by xrosecky** [comment]
Subresource ?website is created, but seems to be ignored by S3:

https://webstortest3.s3.amazonaws.com/?website
http://webstortest3.s3-website-us-east-1.amazonaws.com/

**Comment by klokan** [comment]
http://stackoverflow.com/questions/8651070/why-are-my-amazon-s3-key-permissions-not-sticking
This is the implementation which seems to run:
https://github.com/boto/boto/blob/bc1ebea127b0512a1f38f068ed8e11194d3c00bb/boto/s3/bucket.py#L1219

**Comment by xrosecky** [comment]
OK, I know where is the problem. Working on fix.

**Comment by xrosecky** [comment]
Fixed in 0c9e4fcb8163569a633d4f4261982bd639fced66.

The problem was that you must use this URL with PUT method and body with website configuration in XML:

https://webstortest3.s3.amazonaws.com/?website

instead of:

https://s3.amazonaws.com/webstortest3?website
