### ISSUE TITLE
TileServer: set "Index Document" as index.html on the bucket

### ISSUE THREAD

**Issue by klokan** [klokan/webstor#19]
We need to set on the bucket the default "Index Document" value.

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTwebsite.html

**Comment by klokan** [comment]
@xrosecky - Could you please check this ASAP??? Thank you!

**Comment by xrosecky** [comment]
It's already done, is it working for you?

I have just created webstortest50 and index.html is present:  

http://webstortest50.s3-website-us-east-1.amazonaws.com/

**Comment by klokan** [comment]
Yes. I am sorry - already implemented. Duplicate for #12.

**Comment by klokan** [comment]
There are other issues with tileserver.json. I will investigate.
