### ISSUE TITLE
MBTiles upload

### ISSUE THREAD

**Issue by klokan** [klokan/webstor#5]
We need to be able to upload tiles packed in the SQLite (.mbtiles) file into Amazon S3.

The task is to add into the wscmd a special option (-t filename.mbtiles) for uploading tiles from the given .mbtiles file.

MBTiles format definition:
https://github.com/mapbox/mbtiles-spec/blob/master/1.1/spec.md

For accessing the SQLite from C++ you may review the code at: https://github.com/StepanKuzmin/QTileStream - an example (it implements HTTP Server listening on port 8080 with no GUI in QT and qmake). We may need to iterate on all tiles in the SQLite table - it must be efficient.

Demo .mbtiles files for tests are:
http://tileserver.maptiler.com/grandcanyon/
http://tiles.mapbox.com/mapbox/map/natural-earth-2
Download (45+60MB) from:
http://dev.klokantech.com/klokan/grandcanyon.mbtiles
http://a.tiles.mapbox.com/v3/mapbox.natural-earth-2.mbtiles

Into the Amazon S3 bucket it should be written in a form equal to unpacked tiles, e.g.: /mbtilesbasename/z/x/y.png or .jpg, where the name is without extension .mbtiles.

BE AWARE: We need the Y coordinates with flipped axis, to get it from the 'tile_row' in the database we need to use equation: ( 2 *\* zoom_level - 1) - tile_row

Format is then exactly the same as our older test .zip file.

**Comment by xrosecky** [comment]
Uploading of tiles is finished, testing and benchmarking is in progress. The example of usage is (to be consistent with wscmd cmdline, I used -a parametr for action and -f for file, but I can modify wscmd to use -t parameter, if you want it):

./wscmd -a uploadMBTiles  -n webstortest -f grandcanyon.mbtiles -T 32 -R 16

**Comment by klokan** [comment]
Vasek, could you please update documentation in README in master and close this ticket, if everything is finished on this work?

**Comment by xrosecky** [comment]
README updated.
